version: "3.9"
services:
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v5
    volumes:
      - ./config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8079:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
#  redis:
#    image: redis:7.2.4-alpine
#    container_name: redis
#    hostname: redis
#    networks:
#      - private
#    ports:
#      - 6379:6379
#    volumes:
#      - ./configs/redis/redis.conf:/etc/redis/redis.conf:ro
#    command: redis-server /etc/redis/redis.conf
